statuses:
- name: ready
  dir: ready
  prioritized: true
- name: doing
  dir: doing
  prioritized: false
- name: done
  dir: done
  prioritized: false
default_priority: med
editor: /usr/bin/nano
id_length: 5
priority:
  auto_compact: false
no_edit_on_new: true
